=== polijicCes3/05-Ejercicio/Ejercicio-05.dtd
<!ELEMENT listacompras (venta+)>
<!ELEMENT venta (ventaacredito | venteinmediata)>
<!ELEMENT ventaacredito (fechafinpago,cantidad)>
<!ELEMENT venteinmediata (cantidad,divisa)>
<!ELEMENT fechafinpago (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT divisa (#PCDATA)>

=== polijicCes3/05-Ejercicio/Ejercicio-05.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE listacompras SYSTEM "Ejercicio-05.dtd">
<listacompras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio-05.xsd">
    <venta>
        <ventainmediata>
            <cantidad>1</cantidad>
            <divisa></divisa>
        </ventainmediata>
    </venta>
    <venta>
        <ventaacredito>
            <fechafinpago>2021-09-04</fechafinpago>
            <cantidad>1</cantidad>
        </ventaacredito>
    </venta>
</listacompras>
